apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # property-like keys; each key maps to a simple value
  player_initial_lives: "5"
  ui_properties_file_name: "user-interface.properties"

  # file-like keys
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
    my_name_pod=kedhar    
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
  user-interfac123e.properties123: |
    color.good=kedhar
    color.bad=buke
    allow.textmode=true
