apiVersion: v1
kind: Pod
metadata:
  name: private-reg-pod
spec:
  containers:
    - name: private-container
      image: adurikedharnadh/private_sample_repo:latest
  imagePullSecrets:
    - name: regcred
