apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: kedharsecret
        mountPath: "/config"
        readOnly: true
  volumes:
  - name: kedharsecret
    secret:
      secretName: new-secret
