apiVersion: v1
kind: Service
metadata:
  name: jenkins-nodeport
  labels:
    app: myjenkins
spec:
  type: NodePort
  selector:
    app: myjenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
