apiVersion: v1
kind: LimitRange
metadata:
  name: jenkins-limitrange
  namespace: my-jenkins
spec:
  limits:
  - default:
      cpu: 0.4
      memory: 250Mi
    defaultRequest:
      cpu: 0.4
      memory: 250Mi  
    type: Container
